/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author akmau
 */
public class MultiUnitConversion extends javax.swing.JFrame {

    /**
     * Creates new form MultiUnitConversion
     */
    public MultiUnitConversion() {
        super("Unit Converter Site");
        initComponents();
        setLocationRelativeTo(null);
        Toolkit tk=Toolkit.getDefaultToolkit();
        Image img = tk.getImage("C:/Users/akmau/Downloads/KMTOM.jpg");
        this.setIconImage(img);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Mypanel = new javax.swing.JPanel();
        lvlInput = new javax.swing.JLabel();
        lvlOutput = new javax.swing.JLabel();
        txtInput = new javax.swing.JTextField();
        txtOutput = new javax.swing.JTextField();
        btnConvert = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();
        radioKM = new javax.swing.JRadioButton();
        radioM = new javax.swing.JRadioButton();
        radioCM = new javax.swing.JRadioButton();
        lvlApplictaionName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Mypanel.setBackground(null);
        Mypanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MypanelMouseClicked(evt);
            }
        });

        lvlInput.setBackground(null);
        lvlInput.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lvlInput.setText("Enter Your Values");

        lvlOutput.setBackground(null);
        lvlOutput.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lvlOutput.setText("Required Values ");

        txtInput.setBackground(null);
        txtInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInputActionPerformed(evt);
            }
        });

        txtOutput.setEditable(false);
        txtOutput.setBackground(null);
        txtOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOutputActionPerformed(evt);
            }
        });

        btnConvert.setBackground(new java.awt.Color(153, 255, 153));
        btnConvert.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnConvert.setText("Convert");
        btnConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(153, 255, 153));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnQuit.setBackground(new java.awt.Color(255, 102, 102));
        btnQuit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnQuit.setText("Quit");
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });

        radioKM.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(radioKM);
        radioKM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        radioKM.setText("Killometers");
        radioKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioKMActionPerformed(evt);
            }
        });

        radioM.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(radioM);
        radioM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        radioM.setText("Meters");
        radioM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMActionPerformed(evt);
            }
        });

        radioCM.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(radioCM);
        radioCM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        radioCM.setText("Centimeters");
        radioCM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCMActionPerformed(evt);
            }
        });

        lvlApplictaionName.setBackground(new java.awt.Color(102, 102, 102));
        lvlApplictaionName.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lvlApplictaionName.setText("Unit Conversion Application");

        javax.swing.GroupLayout MypanelLayout = new javax.swing.GroupLayout(Mypanel);
        Mypanel.setLayout(MypanelLayout);
        MypanelLayout.setHorizontalGroup(
            MypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MypanelLayout.createSequentialGroup()
                .addComponent(btnQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(lvlApplictaionName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(MypanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(MypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MypanelLayout.createSequentialGroup()
                        .addComponent(btnConvert)
                        .addGap(95, 95, 95)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77))
                    .addGroup(MypanelLayout.createSequentialGroup()
                        .addGroup(MypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(MypanelLayout.createSequentialGroup()
                                .addComponent(lvlOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71)
                                .addComponent(txtOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(MypanelLayout.createSequentialGroup()
                                .addComponent(lvlInput, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87)
                                .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37)))
                .addGroup(MypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(radioKM)
                        .addComponent(radioM, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MypanelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(radioCM)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        MypanelLayout.setVerticalGroup(
            MypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MypanelLayout.createSequentialGroup()
                .addGroup(MypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnQuit)
                    .addGroup(MypanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lvlApplictaionName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(MypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MypanelLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(MypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lvlInput, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75)
                        .addGroup(MypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lvlOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addGroup(MypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnConvert)
                            .addComponent(btnClear))
                        .addGap(106, 106, 106))
                    .addGroup(MypanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(radioKM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioCM)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Mypanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Mypanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MypanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MypanelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_MypanelMouseClicked

    private void btnConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertActionPerformed
        try {
            //get input text
            String input=txtInput.getText().trim();
            //if input is empty
            if(input.isEmpty()){
                JOptionPane.showMessageDialog(this,"Please enter a value!","Input Missing",JOptionPane.WARNING_MESSAGE);
                return;
            }
            //try parsing numeric value
            double inputValue=Double.parseDouble(input);
            double result=0;
            //check if radio button is selected
            if(radioKM.isSelected()){
                result=inputValue*1000;
                txtOutput.setText(result+"  M");
            }else if(radioM.isSelected()){
                result=inputValue*100;
                txtOutput.setText(result+"  CM");
            }else if(radioCM.isSelected()){
                result=inputValue/100;
                txtOutput.setText(result+"  M");
            }else{
                JOptionPane.showMessageDialog(this,"please select a unit convertor!","No Unit Selected",JOptionPane.WARNING_MESSAGE);
            }
            
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this,"Please select unit convert or valid Number!","No Unit Selected or Invalid Number",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnConvertActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtInput.setText("");
        txtOutput.setText("");
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_btnClearActionPerformed

    private void radioKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioKMActionPerformed
        // TODO add your handling code here:
        lvlOutput.setText("Converted to Meters");
    }//GEN-LAST:event_radioKMActionPerformed

    private void radioMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMActionPerformed
        // TODO add your handling code here
         lvlOutput.setText("Converted to Centimeters");
    }//GEN-LAST:event_radioMActionPerformed

    private void radioCMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCMActionPerformed
        // TODO add your handling code here:
         lvlOutput.setText("Converted to Meters");
    }//GEN-LAST:event_radioCMActionPerformed

    private void txtInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInputActionPerformed

    private void txtOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOutputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOutputActionPerformed

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        // TODO add your handling code here:
        //ask if user really want to quit
        int confirm=JOptionPane.showConfirmDialog(this,"Are you sure you want to exit?","Conform Exit",JOptionPane.YES_NO_OPTION);
        if(confirm==JOptionPane.YES_OPTION){
            //ask name
            String name=JOptionPane.showInputDialog(this,"Please enter your name:");
            
            if(name!=null && !name.trim().isEmpty()){
                JOptionPane.showMessageDialog(this,"Thank You "+name+" for using this Application");
            }else{
                JOptionPane.showMessageDialog(this,"Thank You for using this Application");
            }
            System.exit(0);
        }
    }//GEN-LAST:event_btnQuitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MultiUnitConversion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MultiUnitConversion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MultiUnitConversion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MultiUnitConversion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MultiUnitConversion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Mypanel;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnConvert;
    private javax.swing.JButton btnQuit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel lvlApplictaionName;
    private javax.swing.JLabel lvlInput;
    private javax.swing.JLabel lvlOutput;
    private javax.swing.JRadioButton radioCM;
    private javax.swing.JRadioButton radioKM;
    private javax.swing.JRadioButton radioM;
    private javax.swing.JTextField txtInput;
    private javax.swing.JTextField txtOutput;
    // End of variables declaration//GEN-END:variables
}
